version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - format: binary

source:
  enabled: true

checksum:
  disable: true

sboms:
  - artifacts: source
