version: 2

# Don't define builds, they will be set on the fly

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - format: binary

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
